baseURL = 'https://www.talktao.cc'
languageCode = 'en-us'
title = "说道"
theme = 'partoo'
publishDir = 'docs'
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
tags = [ "minimal", "responsive", "blog","light", "clean", "search"]
features = ["disqus", "site search", "responsive", "google analytics", "side bar"]

# Enable Disqus
disqusShortname = "talktao"

# Google Analytics
googleAnalytics = "G-L57MVQGWSV"

# Syntax highlighting
# pygmentsUseClasses = true   
# pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = true
[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
    lineNoStart=1
    lineNos=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

